### ISSUE TITLE
Finalize product

### ISSUE THREAD

**Issue by dan-koller** [dan-koller/winvpn#1]
# Overview

The app is currently in a working mvp status. However, to finalize the product and release it, there are several aspects and tasks, which have to be considered.

## Tasks 📝

- [x] Clean up code
- [X] Populate `TorView`...
- [x] ... and `SettingsView`

## Improvements 📈

- [x] Address compiler warnings (nullables, etc.)
- [x] Add an issue template that informs users to include the output of the logger in the `log.txt` file

## Bugs 🐞

- [x] Running the app creates a "VPN" directory in the root directory and in `bin/debug/net-8.0/`
- [x] Fullscreen mode doesn't respect the users taskbar location => Taskbar on top is overflowing the app while on the bottom there is a similar sized gap
